version: '3'
services:
  wyoming-whisper:
    build:
      context: ./whisper/
      dockerfile: NONGPU.Dockerfile
    ports:
      - "10300:10300"
    volumes:
      - ./whisper-data:/data
    command: [ "--model", "medium-int8", "--language", "en" ]
    restart: unless-stopped
